name: CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Deploy and Run Application
      run: |
        echo "Stopping existing application..."
        pkill -f 'java -jar' || true  # Dừng ứng dụng cũ (nếu đang chạy)
        
        echo "Deploying new version..."
        JAR_FILE=$(ls target/*.jar | head -n 1)  # Lấy file .jar mới nhất từ target/
        cp "$JAR_FILE" ~/app.jar  # Copy file .jar vào thư mục chung
        chmod +x ~/app.jar  # Cấp quyền thực thi cho file .jar
        echo "Starting new application..."
        nohup java -jar ~/app.jar > ~/app.log 2>&1 &
      
      working-directory: ${{ github.workspace }}
